#!/bin/bash

set -euo pipefail

project_root="$(dirname $0)/../.."

# Redirect output to stderr.
exec 1>&2

${project_root}/gradlew spotlessApply

# optionally add reformatted files to the index
reformatted_files="$(git ls-files --modified)"
if [ '' != "${reformatted_files}" ]; then
    for f in ${reformatted_files}; do
        echo "WARNING: automatic reformatting applied to ${f}"
    done
    echo "ERROR: aborting commit command due to formatting errors, please review and add them to the index to continue"
    exit 1
fi
