#!/bin/bash

set -euo pipefail

project_root="$(dirname $0)/../.."

silent_gradle(){
    set +e
    ${project_root}/gradlew -q ${1} 2>&1 > /dev/null
    set -e
}

# Redirect output to stderr.
exec 1>&2

silent_gradle spotlessCheck
if [ 1 == $? ]; then
    silent_gradle spotlessApply
    echo "ERROR: aborting commit command due to formatting errors, please review local changes and add them to the index to continue"
    exit 1
fi

