---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elastic-otel-java-snapshot
  description: Buildkite Snapshot pipeline for elastic-otel-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elastic-otel-java-snapshot
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elastic-otel-java-snapshot
    spec:
      repository: elastic/elastic-otel-java
      pipeline_file: ".buildkite/snapshot.yml"
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: buildkite-pipeline-elastic-otel-java-release
  description: Buildkite Release pipeline for elastic-otel-java
  links:
    - title: Pipeline
      url: https://buildkite.com/elastic/elastic-otel-java-release
spec:
  type: buildkite-pipeline
  owner: group:apm-agent-java
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: elastic-otel-java-release
    spec:
      repository: elastic/elastic-otel-java
      pipeline_file: ".buildkite/release.yml"
      provider_settings:
        trigger_mode: none
      teams:
        apm-agent-java:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots:
          access_level: MANAGE_BUILD_AND_READ
        observablt-robots-automation:
          access_level: BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
