file_format: "1.0"
resource:
  attributes:
  #     use this to set custom resource attributes
  #    - name: custom.attribute
  #      value: custom.attribute.value

  # get attributes from OTEL_RESOURCE_ATTRIBUTES environment variable if set
  attributes_list: ${OTEL_RESOURCE_ATTRIBUTES:-}

  detection/development:
    detectors:
      # Enable cloud provider resource attributes detectors by default for easier onboarding.
      # Those may slow down application startup, thus only the relevant ones should be enabled in production
      - aws:
      - azure:
      - gcp:
      # Provides 'process.*' attributes, including 'process.pid'
      - process:
      # Provides 'host.id'
      - host:
      # Provides 'container.id'
      - container:
      # Provides 'service.name' and 'service.instance.id'
      - service:

propagator:
  composite:
    - tracecontext:
    - baggage:

tracer_provider:
  processors:

    # Add some baggage entries as span attributes, wildcards are supported.
    # While both included/excluded can be used, we recommend using 'included' to opt-in only for relevant baggage entries.
    - baggage:
        included: [ 'example-baggage-key-*' ]

    # Requires the span-stacktrace extension (included in EDOT)
    # https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/span-stacktrace
    # Adding it before inferred spans processor allows to avoid having to filter inferred spans that
    # do not have a stack trace because they are created from sampling data.
    - stacktrace/development:

    # Requires the inferred-spans extension (included in EDOT)
    # https://github.com/open-telemetry/opentelemetry-java-contrib/tree/main/inferred-spans
    - inferred_spans/development:
        # disabled by default, opt-in
        enabled: ${OTEL_INFERRED_SPANS_ENABLED:-false}
        # avoid log messages about missing JVM symbols by default
        logging_enabled: ${OTEL_INFERRED_SPANS_LOGGING_ENABLED:-false}

    # Batch span exporter, must come last
    - batch:
        exporter:
          # get endpoint from OTEL_EXPORTER_OTLP_ENDPOINT environment variable if set, otherwise fallback to local collector
          # get endpoint headers (like authentication) from OTEL_EXPORTER_OTLP_HEADERS environment variable if set
          otlp_http:
            endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://localhost:4318}/v1/traces
            headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}
          # use the following for grpc
          # otlp_grpc:
          #  endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
          #  headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}

  # Sampler, parent-based with 100% sampling rate by default
  sampler:
    composite/development:
      rule_based:
        rules:
          # filter-out noisy spans from span attributes provided on span start
          # example 1: filter on user-agent header
          - attribute_patterns:
              key: user_agent.original
              included: [ 'example-noisy-user-agent/*']
            sampler:
              always_off:
          # example 2: filter on HTTP request path
          - attribute_patterns:
              key: url.path
              included: [ '/health*']
            sampler:
              always_off:
          # example 3: filter on messaging destination
          - attribute_patterns:
              key: messaging.destination.name
              included: [ 'example-noisy-destination/*']
            sampler:
                always_off:
          # default sampler after rules filtering: parent-based with 100% sampling rate
          - sampler:
              parent_threshold:
                root:
                  probability/development:
                    ratio: 1.0

meter_provider:
  readers:
    - periodic:
        exporter:
          # get endpoint from OTEL_EXPORTER_OTLP_ENDPOINT environment variable if set, otherwise fallback to local collector
          # get endpoint headers (like authentication) from OTEL_EXPORTER_OTLP_HEADERS environment variable if set
          otlp_http:
            endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://localhost:4318}/v1/metrics
            headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}
            temporality_preference: ${OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:-delta}
          # use the following for grpc
          # otlp_grpc:
          #  endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
          #  headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}
          #  temporality_preference: ${OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE:-delta}

logger_provider:
  processors:

    # Add some baggage entries as log attributes, wildcards are supported
    # While both included/excluded can be used, we recommend using 'include' to opt-in only for relevant baggage entries.
    - baggage:
        included: [ 'example-baggage-key-*' ]

    # Batch log exporter, must come last
    - batch:
        exporter:
          # get endpoint from OTEL_EXPORTER_OTLP_ENDPOINT environment variable if set, otherwise fallback to local collector
          # get endpoint headers (like authentication) from OTEL_EXPORTER_OTLP_HEADERS environment variable if set
          otlp_http:
            endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:-http://localhost:4318}/v1/logs
            headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}
          # use the following for grpc
          # otlp_grpc:
          #  endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
          #  headers_list: ${OTEL_EXPORTER_OTLP_HEADERS}

instrumentation/development:
  java:
    runtime_telemetry:
      # emit not-yet stable runtime telemetry metrics which are currently part of semconv for java runtime
      emit_experimental_metrics/development: ${OTEL_INSTRUMENTATION_RUNTIME_TELEMETRY_EMIT_EXPERIMENTAL_METRICS:-true}
    agent:
      experimental:
        # enable experimental indy instrumentation
        indy: true
