agents:
  provider: "gcp"
  image: "family/elastic-otel-java-ubuntu-2204"

steps:
  - label: "Build and publish release"
    key: "release"
    commands: .ci/release.sh
    artifact_paths:
      - "release.txt"
      - "agent/build/libs/elastic-otel-javaagent-*.jar"
      - "jvmti-access/build/libs/jvmti-access-.*.jar"
      - "universal-profiling-integration/build/libs/universal-profiling-integration-.*.jar"
      - "build/dry-run-maven-repo.tgz"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'

