agents:
  provider: "gcp"
  image: "family/elastic-otel-java-ubuntu-2204"

env:
  TARBALL_FILE: ${TARBALL_FILE:-artifacts.tar}

steps:
  - label: "Build and publish snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "build/dry-run-maven-repo.tgz"
      - "${TARBALL_FILE}"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'

