agents:
  provider: "gcp"
  image: "family/elastic-otel-java-ubuntu-2204"

steps:
  - label: "Build and publish snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "agent/build/libs/elastic-otel-javaagent-*.jar"
      - "agentextension/build/libs/elastic-otel-agentextension-.*.jar"
      - "common/build/libs/common-.*.jar"
      - "inferred-spans/build/libs/inferred-spans-.*.jar"
      - "build/dry-run-maven-repo.tgz"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'

