agents:
  provider: "gcp"
  image: "family/elastic-otel-java-ubuntu-2204"

env:
  TARBALL_FILE: ${TARBALL_FILE:-dist.tar}

steps:
  - label: "Build and publish snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "agent/build/libs/elastic-otel-javaagent-*.jar"
      - "jvmti-access/build/libs/jvmti-access-.*.jar"
      - "universal-profiling-integration/build/libs/universal-profiling-integration-.*.jar"
      - "agentextension/build/libs/elastic-otel-agentextension-.*.jar"
      - "common/build/libs/common-.*.jar"
      - "inferred-spans/build/libs/inferred-spans-.*.jar"
      - "build/dry-run-maven-repo.tgz"
      - "${TARBALL_FILE}"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'

