agents:
  provider: "gcp"

steps:
  - label: "Run the snapshot"
    key: "release"
    commands: .ci/snapshot.sh
    artifact_paths:
      - "snapshot.txt"
      - "./agent/build/libs/elastic-otel-javaagent-*.jar"

notify:
  - slack: "#apm-agent-java"
    if: 'build.state != "passed"'

