
[versions]
junit = "5.10.0"
autoservice = "1.1.1"

opentelemetrySdk = "1.29.0"
opentelemetryJavaagent = "1.30.0"
opentelemetryJavaagentAlpha = "1.30.0-alpha"
opentelemetryContribAlpha = "1.30.0-alpha"

[libraries]

[bundles]

[plugins]
