/*
 * Licensed to Elasticsearch B.V. under one or more contributor
 * license agreements. See the NOTICE file distributed with
 * this work for additional information regarding copyright
 * ownership. Elasticsearch B.V. licenses this file to you under
 * the Apache License, Version 2.0 (the "License"); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package co.elastic.opamp.client;

import co.elastic.opamp.client.internal.OpampClientImpl;
import co.elastic.opamp.client.internal.state.AgentDescriptionState;
import co.elastic.opamp.client.internal.state.CapabilitiesState;
import co.elastic.opamp.client.internal.state.InstanceUidState;
import co.elastic.opamp.client.internal.state.OpampClientState;
import co.elastic.opamp.client.internal.state.RemoteConfigStatusState;
import co.elastic.opamp.client.internal.state.SequenceNumberState;
import co.elastic.opamp.client.request.service.HttpRequestService;
import co.elastic.opamp.client.request.service.RequestService;
import co.elastic.opamp.client.request.service.WebSocketRequestService;
import co.elastic.opamp.client.state.State;
import opamp.proto.Anyvalue;
import opamp.proto.Opamp;

/** Builds an {@link OpampClient} instance. */
public final class OpampClientBuilder {
  private final RemoteConfigStatusState remoteConfigStatusState = RemoteConfigStatusState.create();
  private final SequenceNumberState sequenceNumberState = SequenceNumberState.create();
  private final AgentDescriptionState agentDescriptionState = AgentDescriptionState.create();
  private final CapabilitiesState capabilitiesState = CapabilitiesState.create();
  private final InstanceUidState instanceUidState = InstanceUidState.createRandom();
  private State<Opamp.EffectiveConfig> effectiveConfigState =
      State.createInMemory(Opamp.EffectiveConfig.newBuilder().build());
  private RequestService service;

  OpampClientBuilder() {}

  /**
   * Sets an implementation of a {@link co.elastic.opamp.client.request.service.RequestService} to
   * handle the request's sending process. There are 2 possible options, either {@link
   * HttpRequestService} to use HTTP, or {@link WebSocketRequestService} to use WebSocket.
   *
   * @param service The request service implementation.
   * @return this
   */
  public OpampClientBuilder setRequestService(RequestService service) {
    this.service = service;
    return this;
  }

  /**
   * Sets the Agent's <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agenttoserverinstance_uid">instance_uid</a>
   * value. A random one is generated by default.
   *
   * @param instanceUid The AgentToServer.instance_uid value.
   * @return this
   */
  public OpampClientBuilder setInstanceUid(byte[] instanceUid) {
    instanceUidState.set(instanceUid);
    return this;
  }

  /**
   * Sets the "service.name" attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param serviceName The service name.
   * @return this
   */
  public OpampClientBuilder setServiceName(String serviceName) {
    addIdentifyingAttribute("service.name", serviceName);
    return this;
  }

  /**
   * Sets the "service.namespace" attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param serviceNamespace The service namespace.
   * @return this
   */
  public OpampClientBuilder setServiceNamespace(String serviceNamespace) {
    addIdentifyingAttribute("service.namespace", serviceNamespace);
    return this;
  }

  /**
   * Sets the "service.version" attribute into the <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">identifying_attributes</a>
   * field.
   *
   * @param serviceVersion The service version.
   * @return this
   */
  public OpampClientBuilder setServiceVersion(String serviceVersion) {
    addIdentifyingAttribute("service.version", serviceVersion);
    return this;
  }

  /**
   * Adds the AcceptsRemoteConfig and ReportsRemoteConfig capabilities to the Client so that the
   * Server can offer remote config values as explained <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">here</a>.
   *
   * @return this
   */
  public OpampClientBuilder enableRemoteConfig() {
    capabilitiesState.add(
        Opamp.AgentCapabilities.AgentCapabilities_AcceptsRemoteConfig_VALUE
            | Opamp.AgentCapabilities.AgentCapabilities_ReportsRemoteConfig_VALUE);
    return this;
  }

  /**
   * Adds the ReportsEffectiveConfig capability to the Client so that the Server expects the
   * Client's effective config report, as explained <a
   * href="https://github.com/open-telemetry/opamp-spec/blob/main/specification.md#agentdescriptionidentifying_attributes">here</a>.
   *
   * @return this
   */
  public OpampClientBuilder enableEffectiveConfigReporting() {
    capabilitiesState.add(Opamp.AgentCapabilities.AgentCapabilities_ReportsEffectiveConfig_VALUE);
    return this;
  }

  /**
   * Sets the effective config state implementation. It should call {@link State#notifyObservers()}
   * whenever it has changes that have not been sent to the server.
   *
   * @param effectiveConfigState The state implementation.
   * @return this
   */
  public OpampClientBuilder setEffectiveConfigState(
      State<Opamp.EffectiveConfig> effectiveConfigState) {
    this.effectiveConfigState = effectiveConfigState;
    return this;
  }

  public OpampClient build() {
    if (service == null) {
      throw new NullPointerException(
          "The request service is not set. You must provide it by calling setRequestService()");
    }
    OpampClientState state =
        new OpampClientState(
            remoteConfigStatusState,
            sequenceNumberState,
            agentDescriptionState,
            capabilitiesState,
            instanceUidState,
            effectiveConfigState);
    return OpampClientImpl.create(service, state);
  }

  private void addIdentifyingAttribute(String key, String value) {
    agentDescriptionState.set(
        Opamp.AgentDescription.newBuilder(agentDescriptionState.get())
            .addIdentifyingAttributes(createKeyValue(key, value))
            .build());
  }

  private Anyvalue.KeyValue createKeyValue(String key, String value) {
    return Anyvalue.KeyValue.newBuilder()
        .setKey(key)
        .setValue(Anyvalue.AnyValue.newBuilder().setStringValue(value).build())
        .build();
  }
}
