#!/usr/bin/env bash
##  This script prepares the Vault context and required tooling
##  for the release and snapshot pipelines.
##
##  NOTE: *_SECRET or *_TOKEN env variables are masked, hence if you'd like to avoid any
##        surprises please use the suffix _SECRET or _TOKEN for those values that contain
##        any sensitive data. Buildkite can mask those values automatically

set -eo pipefail

# Upload should not do much with the pre-command.
if [[ "$BUILDKITE_COMMAND" =~ .*"upload".* ]]; then
  echo "Skipped pre-command when running the Upload pipeline"
  exit 0
fi

if [ "$BUILDKITE_PIPELINE_SLUG" == "elastic-otel-java-snapshot" ]; then
  source .buildkite/hooks/prepare-release.sh
fi

if [ "$BUILDKITE_PIPELINE_SLUG" == "elastic-otel-java-release" ]; then
  source .buildkite/hooks/prepare-release.sh
fi

# Configure the java version
VERSION=$(cat .java-version)
## TODO: Elasticsearch team uses JAVA_HOME="$HOME/.java/$ES_BUILD_JAVA"
##       maybe we can use the same path.
JAVA_HOME="/usr/java/openjdk$VERSION"
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH

# Validate the java version
java -version
