////
Goal of this doc:
The user is able to successfully see data from their Java application make it to the Elastic UI via the Elastic Distribution for OpenTelemetry Java

Assumptions we're comfortable making about the reader:
* They are familiar with Elastic
* They are familiar with OpenTelemetry
* They have Java installed
////

[[get-started]]
== Get started

:language: Java
:language_lc: java
:distro_name: Elastic Distribution for OpenTelemetry {language}

include::release-status.asciidoc[]

This guide shows you how to use the Elastic Distribution for OpenTelemetry {language} ("the distro") to instrument your {language} application and send OpenTelemetry data to an Elastic Observability deployment.

This doc will guide you through the minimal configuration options to get the Elastic distro set up in your application.
You do _not_ need any existing experience with OpenTelemetry to set up the Elastic distro initially.
If you need more control over your configuration after getting set up, you can learn more in https://opentelemetry.io/docs/languages/net[OpenTelemetry SDK documentation].

[NOTE]
====
As an OpenTelemetry SDK, the distro supports sending data to any OpenTelemetry protocol (OTLP) endpoint (https://opentelemetry.io/docs/collector/[OpenTelemetry Collector]), but this guide assumes you are sending data to Elastic.
====

////
✅ What the user needs to know and/or do before they install the distro
////
[discrete]
[[get-started-prerequisites]]
=== Prerequisites

Before getting started, you'll need somewhere to send the gathered OpenTelemetry data, so it can be viewed and analyzed. This doc assumes you're using an https://www.elastic.co/observability[Elastic Observability] cloud deployment. You can use an existing one or set up a new one.
[[elastic-observability-setup]]
[%collapsible]
.*Expand for setup instructions*
====
To create your first Elastic Observability deployment:

. Sign up for a https://cloud.elastic.co/registration[free Elastic Cloud trial] or sign into an existing account.
. Go to https://cloud.elastic.co/home.
. Click *Create deployment*.
. When the deployment is ready, click *Open* to visit your {kib} home page (for example, `https://{DEPLOYMENT_NAME}.kb.{REGION}.cloud.es.io/app/home#/getting_started`).
====

////
✅ How to install the distro
////
[discrete]
[[get-started-install]]
=== Install

////
✅ Step-by-step instructions
////
To get started with the distro:

. Download the https://mvnrepository.com/artifact/co.elastic.otel/elastic-otel-javaagent/latest[latest release].
. Run the distro using the `-javaagent:` JVM argument with the path to the distro jar:
+
[source,bash]
----
java -javaagent:/path/to/agent.jar \
-jar myapp.jar
----

////
This is true for the .NET distro,
is it also true for the Java distro?

[NOTE]
.The Elastic distro and the OpenTelemetry SDK
====
The distro includes a transitive dependency on the OpenTelemetry SDK, so you do not _need_ to add the
OpenTelemetry SDK package to your project directly. However, you _can_ explicitly add the OpenTelemetry SDK as a dependency if you want to opt into newer SDK versions. If you do this, the OpenTelemetry SDK dependency must
be defined _before_ the {distro_name} is defined.
====
////

////
✅ Start-to-finish operation
////
[discrete]
[[get-started-send-data]]
=== Send data to Elastic

After installing the distro, configure and initialize it to start
sending data to Elastic.

////
✅ Provide _minimal_ configuration/setup
////
[discrete]
[[get-started-configure]]
==== Configure the distro

////
✅ Step-by-step instructions
////
To configure the distro, at a minimum you'll need your Elastic Observability cloud deployment's OTLP endpoint and
authorization data to set the appropriate `OTLP_*` environment variables:

* `OTEL_EXPORTER_OTLP_ENDPOINT`: The full URL of the endpoint where data will be sent.
* `OTEL_EXPORTER_OTLP_HEADERS`: A comma-separated list of `key=value` pairs that will
be added to the headers of every request. This is typically this is used for
<<configure-auth-methods,authentication information>>.

include::./configure.asciidoc[tag=get-auth]

////
✅ What success looks like
////
[discrete]
[[get-started-confirm]]
=== Confirm that the distro is working

To confirm that the distro has successfully connected to Elastic:

. Go to *APM* → *Traces*.
. You should see the name of the service to which you just added the distro.
It can take several minutes after initializing the distro for the service to show up in this list.
. Click on the name in the list to see trace data.
+
NOTE: There may be no trace data to visualize unless you have _used_ your application since
initializing the distro.

////
✅ What they should do next
////
[discrete]
[[get-started-next-steps]]
=== Next steps

* <<configure,Configure the distro>> to send data to Elastic.
* Learn more about viewing and interpreting data in the {observability-guide}/apm.html[Observability guide].

:!language:
:!language_lc:
:!distro_name:
