////
Goal of this doc:
The user is able to successfully see data from their Java application make it to the Elastic UI via the Elastic Distribution for OpenTelemetry Java

Assumptions we're comfortable making about the reader:
* They are familiar with Elastic
* They are familiar with OpenTelemetry
* They have Java installed
////

[[get-started]]
== Get started

:language: Java
:language_lc: java
:distro_name: Elastic Distribution for OpenTelemetry {language}

include::release-status.asciidoc[]

This guide shows you how to use the Elastic Distribution for OpenTelemetry {language} ("the distro") to instrument your {language} application and send OpenTelemetry data to an Elastic Observability deployment.

[NOTE]
====
As an OpenTelemetry SDK, the distro supports sending data to any OpenTelemetry protocol (OTLP) endpoint (https://opentelemetry.io/docs/collector/[OpenTelemetry Collector]), but this guide assumes you are sending data to Elastic.
====

////
✅ What the user needs to know and/or do before they install the distro
////
[discrete]
[[get-started-prerequisites]]
=== Prerequisites

Before getting started:

// Familiarity with OpenTelemetry
* *Familiarize yourself with the OpenTelemetry SDK.* The distro is a lightweight wrapper around the OpenTelemetry SDK. You should be broadly familiar with the OpenTelemetry SDK concepts and instrumenting applications using the Microsoft diagnostic APIs. If you are not familiar with this, start with the https://opentelemetry.io/docs/languages/net[OpenTelemetry SDK documentation].
+
* *Set up Elastic Observability*. You'll need somewhere to send the gathered OpenTelemetry data, so it can be viewed and analyzed. This doc assumes you're using an https://www.elastic.co/observability[Elastic Observability] cloud deployment. You can use an existing one or set up a new one.
+
[[elastic-observability-setup]]
[%collapsible]
.*Expand for setup instructions*
====
This section shows how to create an https://www.elastic.co/observability[Elastic Observability] cloud deployment and get the data you need to configure the distro to send data to it.

. Register at https://cloud.elastic.co/registration[cloud.elastic.co], if you haven't already. This supports starting **free trial**.
. After registering, click *Create deployment* at `<https://cloud.elastic.co/home>`.
. Once that is created, click *Open* to visit your Kibana home page, e.g. `https://{DEPLOYMENT_NAME}.kb.{REGION}.cloud.es.io/app/home#/getting_started`.
====

////
TO DO:
Anything else they need to do/have/know?
For example, any dependencies (including specific supported Java versions)?
////

////
✅ How to install the distro
////
[discrete]
[[get-started-install]]
=== Install

////
✅ Step-by-step instructions
////
To get started with the distro:

. Download the https://mvnrepository.com/artifact/co.elastic.otel/elastic-otel-javaagent/latest[latest release].
. Run the distro using the `-javaagent:` JVM argument with the path to the distro jar:
+
[source,bash]
----
java -javaagent:/path/to/agent.jar \
-jar myapp.jar
----

////
✅ Any additional info related to installation
////
[NOTE]
.The Elastic distro and the OpenTelemetry SDK
====
The distro includes a transitive dependency on the OpenTelemetry SDK, so you do not _need_ to add the
OpenTelemetry SDK package to your project directly. However, you _can_ explicitly add the OpenTelemetry SDK as a dependency if you want to opt into newer SDK versions. If you do this, the OpenTelemetry SDK dependency must
be defined _before_ the {distro_name} is defined.
====

////
✅ Start-to-finish operation
////
[discrete]
[[get-started-send-data]]
=== Send data to Elastic

After installing the distro, configure and initialize it to start
sending data to Elastic.

////
TO DO:
Are there any dependencies that need to be installed in addition to the distro?
If yes, does it matter in what order dependencies are defined?
If no, delete this section.
////
[discrete]
[[get-started-add-dependencies]]
==== Add dependencies

////
Step-by-step instructions
////

////
TO DO:
What does the _minimal_ configuration / setup look like?
Are there any configuration options that are _required_?
////
[discrete]
[[get-started-configure]]
==== Configure the distro

////
Step-by-step instructions
////

////
TO DO:
Does the user need to do something after configuring the distro
for data to start being sent Elastic?
If no, delete this section.
////
[discrete]
[[get-started-initialization]]
==== Initialize the distro

////
Step-by-step instructions
////

////
Optional: Add an image
////

////
TO DO:
What should they expect to see after running this?
How do they know it worked as expected?
////
[discrete]
[[get-started-view-traces]]
=== View traces

To view the traces, you can use the Elastic APM UI:

////
Step-by-step instructions
////

////
✅ What they should do next
////
[discrete]
[[get-started-next-steps]]
=== Next steps

* <<configuration,Configure the distro>> to send data to Elastic.
* Learn more about viewing and interpreting data in the {observability-guide}/apm.html[Observability guide].

:!language:
:!language_lc:
:!distro_name:
