[[landing-page]]
== Elastic Distribution for OpenTelemetry Java

++++
<titleabbrev>Introduction</titleabbrev>
++++

.Alpha release
[WARNING]
====
This project is not yet recommended for production use.
Functionality may be changed or removed in future releases.
Alpha releases are not subject to the support SLA of official GA features.

We welcome your feedback! You can reach us by https://github.com/elastic/elastic-otel-java/issues[opening an issue] or starting a discussion thread on the https://discuss.elastic.co/tags/c/observability/apm/58/java[Elastic Discuss forum].
====

The Elastic Distribution for OpenTelemetry Java (the "Distro") is a Java
package that provides:

* an easy way to instrument your application with OpenTelemetry
* configuration defaults for best usage

Use the Distro to start the OpenTelemetry SDK with your Java application to automatically
capture tracing data, performance metrics, and logs. Traces, metrics, and logs are sent
to any OTLP collector you choose. Use an https://www.elastic.co/observability[Elastic Observability]
deployment–hosted in Elastic's cloud or on-premises–to monitor your applications, create alerts,
and quickly identify root causes of service issues.