name: changelog-submit

on:
  workflow_run:
    workflows: [changelog-init]
    types:
      - completed

permissions:
  contents: read

jobs:
  submit:
    permissions:
      contents: write
      pull-requests: write
    uses: elastic/docs-actions/.github/workflows/changelog-submit.yml@v1
