name: changelog-validate

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  validate:
    uses: elastic/docs-actions/.github/workflows/changelog-validate.yml@v1
