name: changelog-submit-upstream-update

on:
  workflow_run:
    workflows: [changelog-validate]
    types:
      - completed

permissions:
  contents: read

jobs:

  # in this step, we would execute a shell script that will generate a dedicated changelog entry for the upstream update
  # and overwrite any prior upstream update to prevent duplicates
  submit:
    permissions:
      contents: write
      pull-requests: write
    # only generate changelog when PR:
    # - and has proper label for upstream update
    # - is not from a fork (as we need to commit and push to it)
    if: >
      contains(github.event.workflow_run.pull_requests[0].labels.*.name, 'changelog:upstream-update')
      && github.event.workflow_run.pull_requests[0].head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permission-contents: write
          permission-pull-requests: write
          repositories: |
            elastic-otel-java
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          token: ${{ steps.get_token.outputs.token }}
      - name: Git setup
        uses: elastic/oblt-actions/git/setup@v1
        with:
          github-token: ${{ steps.get_token.outputs.token }}
      # gradle wrapper is used in the script to generate changelog entry
      - name: Check gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: Docs builder setup
        uses: elastic/docs-actions/docs-builder/setup@v1

      - name: Generate changelog entry
        env:
          PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number }}
          PR_TITLE: ${{ github.event.workflow_run.pull_requests[0].title }}
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].html_url }}
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          temp_dir="$(mktemp -d)"
          docs-builder changelog add
            --concise
            --title "${PR_TITLE}"
            --type enhancement \
            --prs "${PR_URL}" \
            --products "edot-java NEXT ga" \
            --output "${temp_dir}" \
            --description "- $("./gradlew" -q changelogUpstreamDependenciesOneLiner)"
          # will overwrite any prior update, if there is any
          mv "${temp_dir}/${PR_NUMBER}.yaml" "./docs/changelog/upstream-update.yaml"
          git add --all
          git commit -m "Add changelog for upstream update"
          git push origin ${{ env.BRANCH_NAME }}
