name: "Issue Labeler"
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

    - name: Get token
      id: get_token
      uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
      with:
        app_id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
        private_key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
        permissions: >-
          {
            "members": "read",
            "organization_projects": "write",
            "issues": "read"
          }

    - name: Add agent-java label
      run: gh issue edit "${NUMBER}" --add-label "agent-java" --repo "${{ github.repository }}"
      env:
        NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - id: is_elastic_member
      uses: elastic/oblt-actions/github/is-member-of@v1
      with:
        github-org: "elastic"
        github-user: ${{ github.actor }}
        github-token: ${{ steps.get_token.outputs.token }}

    - name: Add community and triage labels
      if: contains(steps.is_elastic_member.outputs.result, 'false') && github.actor != 'dependabot[bot]' && github.actor != 'elastic-renovate-prod[bot]' && github.actor != 'elastic-observability-automation[bot]'
      run: gh issue edit "${NUMBER}" --add-label "community,triage" --repo "${{ github.repository }}"
      env:
        NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Add comment for community PR
      if: contains(steps.is_elastic_member.outputs.result, 'false') && github.actor != 'dependabot[bot]' && github.actor != 'elastic-renovate-prod[bot]' && github.actor != 'elastic-observability-automation[bot]'
      uses: wow-actions/auto-comment@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        pullRequestOpened: |
          👋 @{{ author }} Thanks a lot for your contribution! 
          
          It may take some time before we review a PR, so even if you don’t see activity for some time, it **does not** mean that we have forgotten about it. 
          
          Every once in a while we go through a process of prioritization, after which we are focussing on the tasks that were planned for the upcoming [milestone](https://github.com/elastic/apm-agent-java/milestones). The prioritization status is typically reflected through the PR labels. It could be pending triage, a candidate for a future milestone, or have a target milestone set to it.

    - name: Assign new internal pull requests to project
      id: add-to-project
      if: contains(steps.is_elastic_member.outputs.result, 'true') && github.event_name == 'pull_request'
      uses: elastic/oblt-actions/github/project-add@v1
      with:
        github-token: ${{ steps.get_token.outputs.token }}
        project-id: 1829
        item-url: ${{ github.event.pull_request.url }}

    - name: set status in project
      id: set-project-status-field
      if: contains(steps.is_elastic_member.outputs.result, 'true') && github.event_name == 'pull_request'
      uses: elastic/oblt-actions/github/project-field-set@v1
      with:
        github-token: ${{ steps.get_token.outputs.token }}
        project-id: 1829
        item-id: ${{ steps.add-to-project.outputs.item-id }}
        field-name: 'Status'
        field-value: 'In Progress'

    - name: set agent in project
      id: set-project-agent-field
      if: contains(steps.is_elastic_member.outputs.result, 'true') && github.event_name == 'pull_request'
      uses: elastic/oblt-actions/github/project-field-set@v1
      with:
        github-token: ${{ steps.get_token.outputs.token }}
        project-id: 1829
        item-id: ${{ steps.add-to-project.outputs.item-id }}
        field-name: 'Agent'
        field-value: 'java'

    - name: set iteration in project
      id: set-project-iteration-field
      if: contains(steps.is_elastic_member.outputs.result, 'true') && github.event_name == 'pull_request'
      uses: elastic/oblt-actions/github/project-field-set@v1
      with:
        github-token: ${{ steps.get_token.outputs.token }}
        project-id: 1829
        item-id: ${{ steps.add-to-project.outputs.item-id }}
        field-name: 'Iteration'
        field-value: '@current'
        field-type: 'iteration'
