---

name: Pre/Post Release
  
on:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag ref to run the workflow on'
        type: string
        required: true
        default: 'main'
      version:
        description: 'The version to release (e.g. 1.2.3). This workflow will automatically perform the required version bumps'
        type: string
        required: true
      phase:
        description: 'Pre or post release phase'
        type: string # valid values are 'pre' or 'post'
        required: true
      pr_title:
        description: 'pull-request title'
        type: string
        required: true
      pr_body:
        description: 'pull-request body'
        type: string
        required: true
      changelog:
        description: 'The changelog to prepend to CHANGELOG.md without heading'
        type: string
        required: false
        default: ''

env:
  RELEASE_VERSION: ${{ inputs.version }}
  BRANCH_NAME: ${{ inputs.phase }}-release-v${{ inputs.version }}

permissions:
  contents: read

jobs:
  validate-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Validate release tag does not exist in repo
        uses: ./.github/workflows/validate-tag
        with:
          tag: v${{ env.RELEASE_VERSION }}
  
  create-pr:
    name: "Bump versions and create PR"
    runs-on: ubuntu-latest
    needs:
      - validate-tag
    steps:

      - name: Get token
        id: get_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private_key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permissions: >-
            {
              "contents": "write",
              "pull_requests": "write"
            }
          repositories: >-
            ["elastic-otel-java"]

      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.ref }}
          token: ${{ steps.get_token.outputs.token }}

      - uses: elastic/oblt-actions/git/setup@v1
        with:
          github-token: ${{ steps.get_token.outputs.token }}

      - name: Create the release tag (post phase)
        if: inputs.phase == 'post'
        run: |
          git tag "v${{ env.RELEASE_VERSION }}"
          git push origin "v${{ env.RELEASE_VERSION }}"
  
      - name: Create a ${{ inputs.phase }} release branch
        run: git checkout -b ${{ env.BRANCH_NAME }}
  
      - name: Set release version (pre release)
        if: inputs.phase == 'pre'
        uses: ./.github/workflows/gradle-goal
        with:
          command: ./gradlew -q setVersion -PnewVersion=${{ env.RELEASE_VERSION }}
  
      - name: Set next snapshot version (post release)
        if: inputs.phase == 'post'
        uses: ./.github/workflows/gradle-goal
        with:
          command: ./gradlew -q setNextVersion

      - name: Insert notes into cumulative changelog (post release)
        if: inputs.phase == 'post'
        run: |
          echo "# ${VERSION} - $(date +'%d/%m/%Y')" > tmpchangelog
          echo "${CHANGELOG}" >> tmpchangelog
          cat CHANGELOG.md >> tmpchangelog
          mv tmpchangelog CHANGELOG.md
        env:
          VERSION: ${{ inputs.version }}
          CHANGELOG: ${{ inputs.changelog }}

      - name: Clear next release changelog (post release)
        if: inputs.phase == 'post'
        run: |
          echo '' > CHANGELOG.next-release.md
  
      - name: Push the ${{ inputs.phase }} release branch
        run: |
          git add --all
          git commit -m "${PHASE} release: elastic-otel-java v${{ env.RELEASE_VERSION }}"
          git push origin ${{ env.BRANCH_NAME }}
        env:
          PHASE: ${{ inputs.phase }}

      - name: Create the ${{ inputs.phase }} release PR
        run: gh pr create --title="${PR_TITLE}" --base main --head ${{ env.BRANCH_NAME }} -b "${PR_BODY}"
        env:
          GH_TOKEN: ${{ steps.get_token.outputs.token }}
          PR_TITLE: ${{ inputs.pr_title }}
          PR_BODY: ${{ inputs.pr_body }}
