name: Changelog file
on:
  workflow_run:
    # Must match the `name:` field of the release-notes workflow in this repo.
    workflows: ["release-notes"]
    types: [completed]
permissions:
  pull-requests: write
  actions: read
jobs:
  changelog-file:
    uses: elastic/docs-actions/.github/workflows/release-notes-changelog-file.yml@v1
