---
name: snapshot

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      dry_run:
        description: If set, run a dry-run snapshot
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      is-snapshot: ${{ steps.validate-step.outputs.is-snapshot }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Warmup gradle wrapper
        uses: ./.github/workflows/gradle-goal
        with:
          command: "./gradlew -q currentVersion"
      - name: Validate version is a snapshot version
        id: validate-step
        run: |
          output=false
          if [[ "$(./gradlew -q currentVersion)" =~ "-SNAPSHOT" ]]; then
            echo "This is a snapshot version"
            output=true
          fi
          echo "is-snapshot=${output}" >> "$GITHUB_OUTPUT"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: 
      - validate
    permissions:
      contents: write
      id-token: write
    env:
      TARBALL_FILE: artifacts.tar
    if: ${{ contains(needs.validate.outputs.is-snapshot, 'true') }}
    steps:
      - id: buildkite
        name: Run Deploy
        uses: elastic/apm-pipeline-library/.github/actions/buildkite@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: elastic-otel-java-snapshot
          pipelineCommit: ${{ github.ref_name }}
          waitFor: true
          printBuildLogs: false
          artifactName: snapshots
          artifactPath: ${{ env.TARBALL_FILE }}
          buildEnvVars: |
            dry_run=${{ inputs.dry_run || 'false' }}
            TARBALL_FILE=${{ env.TARBALL_FILE }}

      - uses: actions/download-artifact@v3
        with:
          name: snapshots

      - name: untar the buildkite tarball
        run: tar xvf ${{ env.TARBALL_FILE }}

      - name: generate build provenance
        uses: github-early-access/generate-build-provenance@main
        with:
          subject-path: "${{ github.workspace }}/**/*.jar"

      - if: ${{ failure() }}
        uses: elastic/apm-pipeline-library/.github/actions/slack-message@current
        with:
          url: ${{ secrets.VAULT_ADDR }}
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          channel: "#apm-agent-java"
          message: |
            :ghost: [${{ github.repository }}] Snapshot *${{ github.ref_name }}* didn't get triggered in Buildkite.
            Build: (<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>)
